version: 2
updates:
  # For GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"  # Refers to the root directory of your repo where your GitHub Actions workflow file is
    schedule:
      interval: "weekly"

  # For npm dependencies updates
  - package-ecosystem: "npm"
    directory: "/"  # This refers to the root directory where package.json is located
    schedule:
      interval: "weekly"  # Check for updates weekly
