version: 2
updates:
  # For GitHub Actions updates
  - package-ecosystem: "github-actions"
    directory: "/"  # Refers to the root directory of your repo where your GitHub Actions workflow file is
    schedule:
      interval: "weekly"

  # For npm dependencies updates (grouped)
  - package-ecosystem: "npm"
    directory: "/"  # Refers to the root directory where package.json is located
    schedule:
      interval: "weekly"  # Check for updates weekly
    commit-message:
      prefix: "deps"  # Set a prefix for the commit message
    groups:
      all-npm-packages:
        patterns:
          - "*"

